<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zqXrCPd' shared service.

return $this->privates['.service_locator.zqXrCPd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\HomeController::ajoutmodif' => ['privates', '.service_locator.zKgxlry', 'get_ServiceLocator_ZKgxlryService.php', true],
    'App\\Controller\\HomeController::delete' => ['privates', '.service_locator.zKgxlry', 'get_ServiceLocator_ZKgxlryService.php', true],
    'App\\Controller\\HomeController:ajoutmodif' => ['privates', '.service_locator.zKgxlry', 'get_ServiceLocator_ZKgxlryService.php', true],
    'App\\Controller\\HomeController:delete' => ['privates', '.service_locator.zKgxlry', 'get_ServiceLocator_ZKgxlryService.php', true],
], [
    'App\\Controller\\HomeController::ajoutmodif' => '?',
    'App\\Controller\\HomeController::delete' => '?',
    'App\\Controller\\HomeController:ajoutmodif' => '?',
    'App\\Controller\\HomeController:delete' => '?',
]);
