<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJB3mM6x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJB3mM6x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJB3mM6x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJB3mM6x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJB3mM6x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JB3mM6x',
    'container.build_id' => 'f40529e1',
    'container.build_time' => 1563206846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJB3mM6x');
