<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Wj3rKK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Wj3rKK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Wj3rKK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Wj3rKK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5Wj3rKK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5Wj3rKK',
    'container.build_id' => '5259ecfa',
    'container.build_time' => 1563186848,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Wj3rKK');
